M48
; DRILL file {KiCad 6.0.11+dfsg-1} date Wed 26 Apr 2023 00:49:19 BST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-26T00:49:19+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X147.11Y-80.605
X147.11Y-119.395
X152.89Y-80.605
X152.89Y-119.395
T0
M30
